import { useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { TimePicker } from '@mui/x-date-pickers/TimePicker';
import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFns'

export default function Home() {

  const [time, setTime] = useState<Date | null>(null);

  const handleChange = (time: Date | null) => {
    if (time) {
      time.setMinutes(0);
    }
    setTime(time);
  }

  return (
    <div>
      <Head>
        <title>Cr eate Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <LocalizationProvider dateAdapter={AdapterDateFns}>
          <TimePicker
            label="開始時間"
            openTo="hours"
            views={['hours']}
            value={time}
            format='HH:00'
            onChange={handleChange}
            ampm={false}
          />
        </LocalizationProvider>
      </main>
    </div>
  )
}
